# Configure game settings
SCREEN_WIDTH = 480
SCREEN_HEIGHT = 320
WINDOW_TITLE = "My First RPG"
INITIAL_MAP = "village.tmx"
PORTAL_INTERACTION_DISTANCE = 16
MENU_MUSIC_FILES = ["background.ogg"]
TILE_SIZE = 16
MENU_TITLE_SIZE = 32
MENU_OPTION_SIZE = 18
MENU_SPACING = 36
INVENTORY_BOX_SIZE = 20
INVENTORY_BOX_SPACING = 5
